use std::fs;
use std::io::Write;
use std::path::Path;

fn collect_lua_files(dir: &Path, prefix: &str, entries: &mut Vec<(String, String)>) {
    if let Ok(read_dir) = fs::read_dir(dir) {
        for entry in read_dir.flatten() {
            let path = entry.path();
            if path.is_dir() {
                let sub_prefix = if prefix.is_empty() {
                    path.file_name().unwrap().to_str().unwrap().to_string()
                } else {
                    format!("{}/{}", prefix, path.file_name().unwrap().to_str().unwrap())
                };
                collect_lua_files(&path, &sub_prefix, entries);
            } else if path.extension().and_then(|e| e.to_str()) == Some("lua")
                && let Some(name) = path.file_name().and_then(|n| n.to_str())
            {
                let key = if prefix.is_empty() {
                    name.to_string()
                } else {
                    format!("{}/{}", prefix, name)
                };
                entries.push((key, path.display().to_string()));
            }
        }
    }
}

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let lua_dir = Path::new(&manifest_dir).join("lua");
    let lua_dir = lua_dir.canonicalize().expect("lua/ directory not found");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("embedded_resources.rs");

    let mut entries: Vec<(String, String)> = Vec::new();
    collect_lua_files(&lua_dir, "", &mut entries);
    entries.sort();

    // Watch each individual lua file so cargo detects content changes
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path);
    }
    // Also watch the directory itself for new/removed files
    println!("cargo:rerun-if-changed={}", lua_dir.display());

    let mut out = fs::File::create(out_path).expect("Failed to create embedded_resources.rs");
    writeln!(out, "// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out, "pub fn lookup(name: &str) -> Option<&'static [u8]> {{").unwrap();
    writeln!(out, "    match name {{").unwrap();
    for (key, _) in &entries {
        let abs_path = lua_dir.join(key);
        writeln!(out, "        \"{}\" => Some(include_bytes!(\"{}\")),", key, abs_path.display()).unwrap();
    }
    writeln!(out, "        _ => None,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "pub fn list() -> Vec<&'static str> {{").unwrap();
    writeln!(out, "    vec![").unwrap();
    for (key, _) in &entries {
        writeln!(out, "        \"{}\",", key).unwrap();
    }
    writeln!(out, "    ]").unwrap();
    writeln!(out, "}}").unwrap();
}
