#![allow(unused)]
pub const CHARACTER_NUL: i32 = 00; // null character
pub const CHARACTER_SOH: i32 = 01; // start of header
pub const CHARACTER_STX: i32 = 02; // start of text
pub const CHARACTER_ETX: i32 = 03; // end of text
pub const CHARACTER_EOT: i32 = 04; // end of transmission
pub const CHARACTER_ENQ: i32 = 05; // enquiry
pub const CHARACTER_ACK: i32 = 06; // acknowledge
pub const CHARACTER_BEL: i32 = 07; // bell (ring)
pub const CHARACTER_BS: i32 = 08; // backspace
pub const CHARACTER_HT: i32 = 09; // horizontal tab
pub const CHARACTER_LF: i32 = 10; // line feed
pub const CHARACTER_VT: i32 = 11; // vertical tab
pub const CHARACTER_FF: i32 = 12; // form feed
pub const CHARACTER_CR: i32 = 13; // carriage return
pub const CHARACTER_SO: i32 = 14; // shift out
pub const CHARACTER_SI: i32 = 15; // shift in
pub const CHARACTER_DLE: i32 = 16; // data link escape
pub const CHARACTER_DC1: i32 = 17; // device control 1
pub const CHARACTER_DC2: i32 = 18; // device control 2
pub const CHARACTER_DC3: i32 = 19; // device control 3
pub const CHARACTER_DC4: i32 = 20; // device control 4
pub const CHARACTER_NAK: i32 = 21; // negative acknowledge
pub const CHARACTER_SYN: i32 = 22; // synchronize
pub const CHARACTER_ETB: i32 = 23; // end transmission block
pub const CHARACTER_CAN: i32 = 24; // cancel
pub const CHARACTER_EM: i32 = 25; // end of medium
pub const CHARACTER_SUB: i32 = 26; // substitute
pub const CHARACTER_ESC: i32 = 27; // escape
pub const CHARACTER_FS: i32 = 28; // file separator
pub const CHARACTER_GS: i32 = 29; // group separator
pub const CHARACTER_RS: i32 = 30; // record separator
pub const CHARACTER_US: i32 = 31; // unit separator
pub const CHARACTER_SPACE: i32 = 32;
pub const CHARACTER_EXCLAMATION: i32 = 33;
pub const CHARACTER_DOUBLEQUOTE: i32 = 34;
pub const CHARACTER_OCTOTHORPE: i32 = 35;
pub const CHARACTER_DOLLAR: i32 = 36;
pub const CHARACTER_PERCENT: i32 = 37;
pub const CHARACTER_AMPERSAND: i32 = 38;
pub const CHARACTER_QUOTE: i32 = 39;
pub const CHARACTER_PARENTHESIS_LEFT: i32 = 40;
pub const CHARACTER_PARENTHESIS_RIGHT: i32 = 41;
pub const CHARACTER_ASTERISK: i32 = 42;
pub const CHARACTER_PLUS: i32 = 43;
pub const CHARACTER_COMMA: i32 = 44;
pub const CHARACTER_HYPHEN: i32 = 45;
pub const CHARACTER_PERIOD: i32 = 46;
pub const CHARACTER_SOLIDUS: i32 = 47;
pub const CHARACTER_0: i32 = 48;
pub const CHARACTER_1: i32 = 49;
pub const CHARACTER_2: i32 = 50;
pub const CHARACTER_3: i32 = 51;
pub const CHARACTER_4: i32 = 52;
pub const CHARACTER_5: i32 = 53;
pub const CHARACTER_6: i32 = 54;
pub const CHARACTER_7: i32 = 55;
pub const CHARACTER_8: i32 = 56;
pub const CHARACTER_9: i32 = 57;
pub const CHARACTER_COLON: i32 = 58;
pub const CHARACTER_SEMICOLON: i32 = 59;
pub const CHARACTER_ANGLE_LEFT: i32 = 60;
pub const CHARACTER_EQUAL: i32 = 61;
pub const CHARACTER_ANGLE_RIGHT: i32 = 62;
pub const CHARACTER_QUESTION: i32 = 63;
pub const CHARACTER_AT: i32 = 64;
pub const CHARACTER_UPPER_A: i32 = 65;
pub const CHARACTER_UPPER_B: i32 = 66;
pub const CHARACTER_UPPER_C: i32 = 67;
pub const CHARACTER_UPPER_D: i32 = 68;
pub const CHARACTER_UPPER_E: i32 = 69;
pub const CHARACTER_UPPER_F: i32 = 70;
pub const CHARACTER_UPPER_G: i32 = 71;
pub const CHARACTER_UPPER_H: i32 = 72;
pub const CHARACTER_UPPER_I: i32 = 73;
pub const CHARACTER_UPPER_J: i32 = 74;
pub const CHARACTER_UPPER_K: i32 = 75;
pub const CHARACTER_UPPER_L: i32 = 76;
pub const CHARACTER_UPPER_M: i32 = 77;
pub const CHARACTER_UPPER_N: i32 = 78;
pub const CHARACTER_UPPER_O: i32 = 79;
pub const CHARACTER_UPPER_P: i32 = 80;
pub const CHARACTER_UPPER_Q: i32 = 81;
pub const CHARACTER_UPPER_R: i32 = 82;
pub const CHARACTER_UPPER_S: i32 = 83;
pub const CHARACTER_UPPER_T: i32 = 84;
pub const CHARACTER_UPPER_U: i32 = 85;
pub const CHARACTER_UPPER_V: i32 = 86;
pub const CHARACTER_UPPER_W: i32 = 87;
pub const CHARACTER_UPPER_X: i32 = 88;
pub const CHARACTER_UPPER_Y: i32 = 89;
pub const CHARACTER_UPPER_Z: i32 = 90;
pub const CHARACTER_BRACKET_LEFT: i32 = 91;
pub const CHARACTER_BACKSLASH: i32 = 92;
pub const CHARACTER_BRACKET_RIGHT: i32 = 93;
pub const CHARACTER_CARET: i32 = 94;
pub const CHARACTER_UNDERSCORE: i32 = 95;
pub const CHARACTER_GRAVE: i32 = 96;
pub const CHARACTER_LOWER_A: i32 = 97;
pub const CHARACTER_LOWER_B: i32 = 98;
pub const CHARACTER_LOWER_C: i32 = 99;
pub const CHARACTER_LOWER_D: i32 = 100;
pub const CHARACTER_LOWER_E: i32 = 101;
pub const CHARACTER_LOWER_F: i32 = 102;
pub const CHARACTER_LOWER_G: i32 = 103;
pub const CHARACTER_LOWER_H: i32 = 104;
pub const CHARACTER_LOWER_I: i32 = 105;
pub const CHARACTER_LOWER_J: i32 = 106;
pub const CHARACTER_LOWER_K: i32 = 107;
pub const CHARACTER_LOWER_L: i32 = 108;
pub const CHARACTER_LOWER_M: i32 = 109;
pub const CHARACTER_LOWER_N: i32 = 110;
pub const CHARACTER_LOWER_O: i32 = 111;
pub const CHARACTER_LOWER_P: i32 = 112;
pub const CHARACTER_LOWER_Q: i32 = 113;
pub const CHARACTER_LOWER_R: i32 = 114;
pub const CHARACTER_LOWER_S: i32 = 115;
pub const CHARACTER_LOWER_T: i32 = 116;
pub const CHARACTER_LOWER_U: i32 = 117;
pub const CHARACTER_LOWER_V: i32 = 118;
pub const CHARACTER_LOWER_W: i32 = 119;
pub const CHARACTER_LOWER_X: i32 = 120;
pub const CHARACTER_LOWER_Y: i32 = 121;
pub const CHARACTER_LOWER_Z: i32 = 122;
pub const CHARACTER_BRACE_LEFT: i32 = 123;
pub const CHARACTER_BAR: i32 = 124;
pub const CHARACTER_BRACE_RIGHT: i32 = 125;
pub const CHARACTER_TILDE: i32 = 126;
pub const CHARACTER_DELETE: i32 = 127;
pub unsafe extern "C" fn get_hexadecimal_digit_value(ch: i32) -> i32 {
    match ch {
        CHARACTER_0 => 0,
        CHARACTER_1 => 1,
        CHARACTER_2 => 2,
        CHARACTER_3 => 3,
        CHARACTER_4 => 4,
        CHARACTER_5 => 5,
        CHARACTER_6 => 6,
        CHARACTER_7 => 7,
        CHARACTER_8 => 8,
        CHARACTER_9 => 9,
        CHARACTER_UPPER_A | CHARACTER_LOWER_A => 10,
        CHARACTER_UPPER_B | CHARACTER_LOWER_B => 11,
        CHARACTER_UPPER_C | CHARACTER_LOWER_C => 12,
        CHARACTER_UPPER_D | CHARACTER_LOWER_D => 13,
        CHARACTER_UPPER_E | CHARACTER_LOWER_E => 14,
        CHARACTER_UPPER_F | CHARACTER_LOWER_F => 15,
        _ => 0,
    }
}
pub const CHARACTER_TYPE_NONE: u8 = 0x00;
pub const CHARACTER_TYPE_IDENTIFIER: u8 = 0x01;
pub const CHARACTER_TYPE_DIGIT_DECIMAL: u8 = 0x02;
pub const CHARACTER_TYPE_PRINTABLE: u8 = 0x04;
pub const CHARACTER_TYPE_WHITESPACE: u8 = 0x08;
pub const CHARACTER_TYPE_DIGIT_HEXADECIMAL: u8 = 0x10;
pub fn get_character_type(ch: i32) -> u8 {
    return CHARACTER_TYPE[ch as usize];
}
pub fn is_whitespace(ch: i32) -> bool {
    return get_character_type(ch) & CHARACTER_TYPE_WHITESPACE != 0;
}
pub fn is_alphanumeric(ch: i32) -> bool {
    return get_character_type(ch) & (CHARACTER_TYPE_IDENTIFIER | CHARACTER_TYPE_DIGIT_DECIMAL) != 0;
}
pub fn is_printable(ch: i32) -> bool {
    return get_character_type(ch) & CHARACTER_TYPE_PRINTABLE != 0;
}
pub fn is_identifier(ch: i32) -> bool {
    return get_character_type(ch) & CHARACTER_TYPE_IDENTIFIER != 0;
}
pub fn is_digit_hexadecimal(ch: i32) -> bool {
    return get_character_type(ch) & CHARACTER_TYPE_DIGIT_HEXADECIMAL != 0;
}
pub fn is_digit_decimal(ch: i32) -> bool {
    return get_character_type(ch) & CHARACTER_TYPE_DIGIT_DECIMAL != 0;
}
const CHARACTER_TYPE: [u8; 257] = [
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_WHITESPACE,
    CHARACTER_TYPE_WHITESPACE,
    CHARACTER_TYPE_WHITESPACE,
    CHARACTER_TYPE_WHITESPACE,
    CHARACTER_TYPE_WHITESPACE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_WHITESPACE | CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL |  CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_DIGIT_DECIMAL,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_DIGIT_HEXADECIMAL | CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE | CHARACTER_TYPE_IDENTIFIER,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_PRINTABLE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
    CHARACTER_TYPE_NONE,
];
pub unsafe extern "C" fn luao_utf8esc(buffer: *mut i8, mut x: u64) -> i32 {
    unsafe {
        let mut n: i32 = 1;
        if x < 0x80 {
            *buffer.offset((8 - 1) as isize) = x as i8;
        } else {
            let mut mfb: u64 = 0x3f;
            loop {
                let fresh9 = n;
                n += 1;
                *buffer.offset((8 - fresh9) as isize) =
                    (0x80 as u64 | x & 0x3f as u64) as i8;
                x >>= 6;
                mfb >>= 1;
                if !(x > mfb) {
                    break;
                }
            }
            *buffer.offset((8 - n) as isize) = ((!mfb << 1) as u64 | x) as i8;
        }
        return n;
    }
}
